[package]
name = "boost_format"
description = "Boost C++ library boost_format packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_format"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_format"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_optional = { version = "0.1.0", path = "../boost_optional" }
boost_smart_ptr = { version = "0.1.0", path = "../boost_smart_ptr" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_utility = { version = "0.1.0", path = "../boost_utility" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
